spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autotest
    username: root
    password: 110110110
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS # 控制台显示带颜色
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true





